# Generated by Django 5.2.4 on 2025-07-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_centrocomercial_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
